plugin_repo:
  type: resource
  name: data/plugins.json
  metadata_provider:
    type: pylon.core.providers.metadata.http
  source_provider:
    type: pylon.core.providers.source.git
    delete_git_dir: false
    depth: null

preordered_plugins:
  - auth
  - admin
  - theme
  - design-system
  - shared
  - projects
  - secrets
  - tasks
  - artifacts
  - scheduling
